### ISSUE TITLE
Ability to queue updates?

### ISSUE THREAD

**Issue by josephfrazier** [tibdex/auto-update#10]
Hey there, thanks for building this! It looks like a great alternative to github's merge queue feature, which isn't generally available yet!

I'm thinking about using auto-update to queue up several dependency bump PRs at a time, but I'm concerned that it will update *all* auto-mergeable PRs each time one is merged, causing undue load on my CI system. Is there a way to queue up the updates so that only the PR for which auto-merge was enabled earliest, gets updated?

If not, I might be willing to add an option for it, if it's possible to tell from the github API the time at which the auto-merge button was clicked.

Thanks!

**Comment by josephfrazier** [comment]
>  if it's possible to tell from the github API the time at which the auto-merge button was clicked.

If this isn't the case, a similar alternative would be to update the PR with the oldest creation time.

**Comment by tibdex** [comment]
Hi Joseph, it's not that simple to implement a queue.
Indeed, if the build of the PR on which auto-merge was enabled first starts failing, you'd want auto-update to fallback to the second oldest PR and so on. So now you need to trigger the action on more event types.

I prefer this action to stay as simple as possible, especially now that GitHub's merge queue has reached a beta state.
If you want to implement a queue, please fork this repo ;)

**Comment by josephfrazier** [comment]
That makes sense to me, I hadn't considered the complexity around build failures. Thanks for the quick response!
