### ISSUE TITLE
Auto-update not triggering CI checks

### ISSUE THREAD

**Issue by ghost** [tibdex/auto-update#16]
Hi.

I have a GH workflow that runs on the following trigger:
```
on:
  pull_request:
    types: [opened, synchronize, ready_for_review]
```

So everytime we push to a PR branch, or click "Update branch" from the PR, it re-runs.

My issue: When auto-update is activated, it updates the branch correctly but no CI check is triggered.

Any idea why?

**Comment by jonrose-dev** [comment]
I'm having the same issue

**Comment by tibdex** [comment]
Hi, mabe [this](https://github.com/tibdex/github-app-token#github-app-token) or [that](https://github.com/tibdex/github-app-token/issues/45) could help.
