### ISSUE TITLE
Ability to configure to also update PRs in draft status

### ISSUE THREAD

**Issue by brianespinosa** [tibdex/auto-update#3]
Currently it appears `auto-update` will only update PRs that are not in Draft state. It would be nice to be able to configure this.

Like my other feature request, let me know if you are open to accepting PRs. Someone on my team or I would be happy to submit one!

**Comment by tibdex** [comment]
Hi Bian,

As explained in the README, I mostly see this action as a way to easily merge PRs without having to manually go back to their dedicated page and click on the Update Branch button to get a fresh green CI. Draft PRs don’t really fit here since they’re used as a way to denote that the work is not ready to be merged yet.

Do you have something else in mind?

**Comment by brianespinosa** [comment]
@tibdex I guess I see the value here as more than just the ability to easily auto merge with Github's new auto feature. Being able to keep feature branches up to date while PRs come into them until they come out of draft status would still be helpful. This needs to happen anyway, and if this happens whenever the target branch is updated, IMO that is a better time for devs to see those updates and potential conflicts than at the end of their work.

I understand that our process might be drifting out of the scope of your initial intentions. I think this would still be valuable to be a configuration option and I agree with updating draft PRs would not be the default and something that you would want to opt-in on.

**Comment by tibdex** [comment]
https://github.com/tibdex/auto-update/commit/f3214295c70ec1baa64262fdd3cdfd4d534cac9a simplifies this action: it removes the need for a label by only looking at pull requests with auto-merge enabled. Draft pull requests cannot have auto-merge enabled so I'm closing this.
